version: '3'
services:
  api:
    build: .
    restart: always
    ports:
      - '8001:8001'
    volumes:
      - .:/home/node/app
    networks:
      - facile
    depends_on:
      - db
  db:
    image: mongo
    restart: always
    container_name: db
    volumes:
      - ./data-node:/data/db
    ports:
      - 27017:27017
    command: mongod --noauth --smallfiles
    networks:
      - facile
networks:
  facile:
    external:
      name: facile
