version: '3'
services:
  api:
    build: .
    ports:
      - '24041:24041'
      - '24051:24051'
    volumes:
      - .:/home/node/store
    entrypoint: 'npm run dev'
    networks:
      - facile
    depends_on:
      - db
  db:
    image: mongo
    restart: always
    container_name: db
    volumes:
      - ./data-node:/data/db
    ports:
      - 27017:27017
    command: mongod --noauth --smallfiles
    networks:
      - facile
networks:
  facile:
    external:
      name: facile
