version: "3"
services:
  web:
    build: .
    restart: always
    ports:
      - "8001:8001"
    volumes:
      - .:/home/node/app
    depends_on:
      - db
    networks:
      - the_network
  db:
    image: mongo
    restart: always
    container_name: db
    volumes:
      - ./data-node:/data/db
    ports:
      - 27017:27017
    command: mongod --noauth --smallfiles
    networks:
      - the_network

networks:
  the_network:
    driver: bridge
